### ISSUE TITLE
run executable within CLI?

### ISSUE THREAD

**Issue by IntrinsicInnovation** [SafeBreach-Labs/CloudMiner#7]
Hi.  is it possible for the python script to call a linux executable program (it would be part of the files to upload to cli from the command prompt)  Its written in another language so it wouldnt be a python script.

Thanks

**Comment by arielgamrian** [comment]
@IntrinsicInnovation CloudMiner does not have any limitations for your custom script. However, there might be some limitations in the Azure container you're running within. That means that your Python script would run in some cases but will fail because of the container limitations. As for your question, you need to give it a shot and debug the results.
